### ISSUE TITLE
Add a list of Moocs and University courses

### ISSUE THREAD

**Issue by hargup** [vivekiitkgp/awesome-biology#2]
MOOCs and University Lectures can be a great way to get started with some area. We should have a list of them.

**Comment by vivekiitkgp** [comment]
Probably in a separate file and linked to the main `README`

**Comment by vivekiitkgp** [comment]
A few which I can find:

1. [Finding Hidden Messages in DNA (Bioinformatics I)](https://www.coursera.org/course/hiddenmessages)
2. [Network Analysis in Systems Biology](https://www.coursera.org/course/netsysbio)
3. [Introduction to Systems Biology](https://www.coursera.org/course/sysbio)
4. [Epigenetic Control of Gene Expression](https://www.coursera.org/course/epigenetics)
5. [Experimental Genome Science](https://www.coursera.org/course/genomescience)
